Homework 7
PauLOk777/vue-js-course pull request #9
Opened 2021-04-27 17:21 UTC by PauLOk777

2021-04-27 17:21 UTC, PauLOk777 commented
Deployment: https://paulok777.github.io/vue-js-course/

2021-04-28 13:42 UTC, Dmitry-White requested changes

2021-04-28 13:42 UTC, Dmitry-White commented on src/core/api.js
> +  getMoviesByParameters(sortBy, sortOrder, search, searchBy, offset, limit) {
When you have so many parameters, it could be more convenient to pass them as an object - that way you won't have to think about their ordering.

2021-04-28 15:51 UTC, Dmitry-White approved these changes

2021-04-28 17:59 UTC, merged